export const CREATE_ANSWER_REQUEST = 'CREATE_ANSWER_REQUEST';
export const CREATE_ANSWER_SUCCESS = 'CREATE_ANSWER_SUCCESS';
export const CREATE_ANSWER_FAILURE = 'CREATE_ANSWER_FAILURE';

export const GET_ALL_ANSWER_REQUEST = 'GET_ALL_ANSWER_REQUEST';
export const GET_ALL_ANSWER_SUCCESS = 'GET_ALL_ANSWER_SUCCESS';
export const GET_ALL_ANSWER_FAILURE = 'GET_ALL_ANSWER_FAILURE';