export const GET_ALL_SYMPTOMS_REQUEST = 'GET_ALL_SYMPTOMS_REQUEST';
export const GET_ALL_SYMPTOMS_SUCCESS = 'GET_ALL_SYMPTOMS_SUCCESS';
export const GET_ALL_SYMPTOMS_FAILURE = 'GET_ALL_SYMPTOMS_FAILURE';

export const GET_ALL_TITLES_REQUEST = 'GET_ALL_TITLES_REQUEST';
export const GET_ALL_TITLES_SUCCESS = 'GET_ALL_TITLES_SUCCESS';
export const GET_ALL_TITLES_FAILURE = 'GET_ALL_TITLES_FAILURE';

export const GET_ALL_DISEASES_BY_TITLE_REQUEST = 'GET_ALL_DISEASES_BY_TITLE_REQUEST';
export const GET_ALL_DISEASES_BY_TITLE_SUCCESS = 'GET_ALL_DISEASES_BY_TITLE_SUCCESS';
export const GET_ALL_DISEASES_BY_TITLE_FAILURE = 'GET_ALL_DISEASES_BY_TITLE_FAILURE';


export const GET_ALL_DISEASES_BY_SYMPTOMS_REQUEST = 'GET_ALL_DISEASES_BY_SYMPTOMS_REQUEST';
export const GET_ALL_DISEASES_BY_SYMPTOMS_SUCCESS = 'GET_ALL_DISEASES_BY_SYMPTOMS_SUCCESS';
export const GET_ALL_DISEASES_BY_SYMPTOMS_FAILURE = 'GET_ALL_DISEASES_BY_SYMPTOMS_FAILURE';

export const GET_ALL_DISEASE_BY_ID_REQUEST = 'GET_ALL_DISEASE_BY_ID_REQUEST';
export const GET_ALL_DISEASE_BY_ID_SUCCESS = 'GET_ALL_DISEASE_BY_ID_SUCCESS';
export const GET_ALL_DISEASE_BY_ID_FAILURE = 'GET_ALL_DISEASE_BY_ID_FAILURE';
