export const GET_ALL_PARAMETERS_REQUEST = 'GET_ALL_PARAMETERS_REQUEST';
export const GET_ALL_PARAMETERS_SUCCESS = 'GET_ALL_PARAMETERS_SUCCESS';
export const GET_ALL_PARAMETERS_FAILURE = 'GET_ALL_PARAMETERS_FAILURE';
