export const GET_PLANTS_BY_PARAMETES_REQUEST = 'GET_PLANTS_BY_PARAMETES_REQUEST';
export const GET_PLANTS_BY_PARAMETES_SUCCESS = 'GET_PLANTS_BY_PARAMETES_SUCCESS';
export const GET_PLANTS_BY_PARAMETES_FAILURE = 'GET_PLANTS_BY_PARAMETES_FAILURE';

export const GET_PLANT_BY_ID_REQUEST = 'GET_PLANT_BY_ID_REQUEST';
export const GET_PLANT_BY_ID_SUCCESS = 'GET_PLANT_BY_ID_SUCCESS';
export const GET_PLANT_BY_ID_FAILURE = 'GET_PLANT_BY_ID_FAILURE';
