export const CREATE_QUESTION_REQUEST = 'CREATE_QUESTION_REQUEST';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_FAILURE = 'CREATE_QUESTION_FAILURE';

export const GET_ALL_QUESTION_REQUEST = 'GET_ALL_QUESTION_REQUEST';
export const GET_ALL_QUESTION_SUCCESS = 'GET_ALL_QUESTION_SUCCESS';
export const GET_ALL_QUESTION_FAILURE = 'GET_ALL_QUESTION_FAILURE';
